server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
#          force-pull: true
#          uri: D:\my_training_projects\book-bench\config
          uri: https://github.com/book-bench/config
